# Generated by Django 2.1.1 on 2018-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpc', '0002_auto_20180904_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='dtype',
            field=models.CharField(choices=[('', ''), ('HDD', 'HDD'), ('SSD', 'SSD')], default='HDD', max_length=100),
        ),
    ]
